
if (!require(udpipe)) {install.packages("udpipe")};  library(udpipe)
if (!require(dplyr)) {install.packages("dplyr")};  library(dplyr)
if (!require(ggplot2)) {install.packages("ggplot2")};  library(ggplot2)
if (!require(stopwords)) {install.packages("stopwords")};  library(stopwords)
if (!require(shinyWidgets)) {install.packages("shinyWidgets")};  library(shinyWidgets)
if (!require(shinydashboard)) {install.packages("shinydashboard")};  library(shinydashboard)
if(!require(lattice)){install.packages('lattice')};library(lattice)
if (!require(shiny)) {install.packages("shiny")};  library(shiny)
if (!require(stringr)) {install.packages("stringr")};  library(stringr)
